# Generated by Django 5.0 on 2025-05-27 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('affected_plant_part', models.CharField(choices=[('leaf', 'Leaf'), ('stem', 'Stem'), ('fruit', 'Fruit'), ('root', 'Root'), ('flower', 'Flower')], max_length=50)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('total_plants', models.PositiveIntegerField()),
                ('area_hectares', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveillanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('plants_checked', models.PositiveIntegerField()),
                ('infected_plants', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('location_in_farm', models.CharField(max_length=100)),
                ('image_evidence', models.ImageField(blank=True, null=True, upload_to='surveillance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.farm')),
                ('pest_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.pestdisease')),
            ],
        ),
    ]
